### ISSUE TITLE
Expose output filename and extension as a handlebar variables

### ISSUE THREAD

**Issue by windgazer** [75lb/jsdoc-to-markdown#18]
I would like to render the jsdocs as separate output files, one output file for each input file. This is easily achieved using the Grunt plugin. However, I would also like to generate an index file that links to these.
I got pretty close using the following snippet in a custom `.hbs`:

```
{{#identifiers~}}{{#each this~}}
{{#if longname}}- [{{{longname}}}](api/{{{name}}}){{/if}}
{{/each~}}{{/identifiers}}
```

The problem being that `{{{name}}}` does not have to match the filename, it accidentally does on most modules, but not on stuff exposed by the modules, for instance. It'd help a lot if the output filename was exposed in a variable available in the handlebars template.

I submit this may actually be a slight abuse of your whole setup and certainly not your primary focus, but it could so easily make this an awesome setup for multi-page wiki's based on markdown!

**Comment by windgazer** [comment]
I'm being an idiot, sorry, this will never work as the index would be generated in a separate run-through where the output filenames would not even be available!

**Comment by 75lb** [comment]
hi, sorry - i’ve not had chance to look at this tonight.. hitting the sack now so will get back to you tomorrow
