### ISSUE TITLE
(branch next) Pipes in table not escaping correctly in NPM markdown

### ISSUE THREAD

**Issue by jesucarr** [75lb/jsdoc-to-markdown#25]
Hey congrats for the upcoming version, I gave it a try and I like it a lot. Great improvements.

I found one little issue when escaping pipes in tables, for example when a value can be {String | Number}. In NPM the markdown doesn't seem to scape the \. You can see an example in my published package: https://www.npmjs.com/package/tokenbucket

After having a quick look it seems that the HTML character (&#124;) should be used instead.

**Comment by 75lb** [comment]
hey! pleased you like the tool... great docs - i will try your library myself.. 

i'm working on making it easier to document promises - will send more info soon.. 

which @param has the broken pipe symbol? i can't see it on your npm or github.. although i know there is an issue as i saw it myself recently..

**Comment by jesucarr** [comment]
[options.interval] and [options.maxWait] have type {Number | String}, and as you can see they create an extra column in the NPM docs (not in Github)

**Comment by 75lb** [comment]
hi Jesu.. ahh yes, i have come across this issue on npm before.. the output generated by jsdoc2md is correct:
```markdown
| [options.interval] | <code>Number</code> \| <code>String</code> |
```
you can see the `|` character between Number and String is escaped - this is why it looks fine on github.. 

the issue is that the npm markdown parser (https://www.npmjs.com/package/marky-markdown) does not fully support gfm tables (yet).. 

the solution is to render your docs using the `--no-gfm` option.. you can see what `no-gfm` output looks like in this example: https://github.com/75lb/jsdoc-to-markdown/tree/next/example/formatting%20options/no-gfm

**Comment by jesucarr** [comment]
I would really like to keep my gfm. Wouldn't be easy to replace `\|` with `&#124;` so it works in both?

**Comment by 75lb** [comment]
if `&#124;` works in both, then yes - let's do that! will implement this evening..

**Comment by 75lb** [comment]
fixed in https://github.com/75lb/dmd/commit/158879534b7b3d1a1223707dd1b4764ee875ae6e, released in dmd 0.3.25.

reinstall to pick up the change:
```
$ npm i jsdoc-to-markdown@next
```

**Comment by 75lb** [comment]
damn.. i released dmd 0.3.25 last night but forgot to update the `next` tag to correctly point to it.. please reinstall, you will see your change now: 
```
$ npm i jsdoc-to-markdown@next
```

**Comment by jesucarr** [comment]
looks beautiful now :) https://www.npmjs.com/package/tokenbucket

**Comment by 75lb** [comment]
it's looking excellent - very nice docs.. on the jsdoc2md readme, could I refer to your library as a good example? 

i'm currently working on an improved way to document promises - will get back to you soon about that..

**Comment by jesucarr** [comment]
Sure you can refer my library. 

I look forward to see the promises improvements.
