### ISSUE TITLE
How to recursively include all files in a directory and it's subdirectories ?

### ISSUE THREAD

**Issue by borisirota** [75lb/jsdoc-to-markdown#26]
I'm using the module from the command line:
`jsdoc2md lib/**/*.js -t readme.hbs > README.md`

I'm using glob expression as noted in the documentation and it works ok as long as `lib` doesn't have subdirectories with files inside.

When adding subdirectory inside `lib` with files the jsdoc2md ignore the files inside `lib` and take into account only the files inside lib's subdirectories.

How to take into account all the files inside `lib` and it's subdirectories ?

Thanks,
Boris

**Comment by 75lb** [comment]
Hi, put the glob expression inside quotes

**Comment by borisirota** [comment]
It works ! Thanks :)

**Comment by 75lb** [comment]
if you wrap the expression in quotes, bash (or your shell) will not attempt file-name expansion on the expression... if you don't use quotes, bash will attempt to expand the expression (which will only work in bash 4 with globstar enabled)

**Comment by borisirota** [comment]
cool thanks :)

**Comment by matteocontrini** [comment]
Hi,
I've tried this but it is going inside the `node_modules` directory too, documenting things I don't care about and even failing with some modules (`gm` for example).
Any way to avoid this?

**Comment by 75lb** [comment]
well, you can pass in several glob expressions enabling you to be specific about what to parse: 

instead of this:
```
$ jsdoc2md "**/*.js"
```
you could be more specific about which folders to traverse: 
```
$ jsdoc2md "src/**/*.js" "test/**/*.js"
```

**Comment by matteocontrini** [comment]
Thanks, I used like this in my case, if it'll help someone.
--> .js files in current folder and "extensions" folder

```
jsdoc2md --example-lang js --verbose *.js extensions/*.js > api.md
```

**Comment by 75lb** [comment]
nice
