### ISSUE TITLE
Suggestion: add ability to generate documentation from jsdoc inside html files

### ISSUE THREAD

**Issue by arodic** [75lb/jsdoc-to-markdown#6]
I'm looking into automatically generating README.md from html elements that contain jsdoc within inline javascript blocks as well within html comment blocks. Would something like this be possible with jsdoc-to-markdown?

**Comment by 75lb** [comment]
sup @arodic .. i packaged up a pre-release version for you to play with.. 

install it
`$ npm install -g jsdoc-to-markdown@next`

then try it for yourself, you must pass the `--html` option for your plugin to be activated: 
`$ jsdoc2md --html index.html`

take a look at the new options:
`$ jsdoc2md --help`

let me know of any flaws etc.. can you suggest some projects with html documentation for me to test against?

**Comment by arodic** [comment]
Hey @75lb 

Thanks for the update. Unfortunately, I was not able to run it (no output). Perhaps some dependencies are missing on my end.

I was going to use this feature for custom elements made with polymerjs such as [this one](https://github.com/Polymer/paper-slider/blob/master/paper-slider.html).

**Comment by 75lb** [comment]
hey :) 

it works fine for me, did you remember to use the required `--html` flag? 

try re-installing: 
`$ npm i -g jsdoc-to-markdown@next`

then generate docs:
`$ jsdoc2md --html paper-slider.html`

**Comment by arodic** [comment]
That did it! I tried it with a bunch of files and it worked perfectly. I'll let you know if I notice any bugs :bug: 

Thanks so much!

**Comment by 75lb** [comment]
you’re welcome.. and thanks for the plugin!=

**Comment by 75lb** [comment]
hey @arodic , do you have any projects which have documentation created using your plug-in? I'm looking for an example to put on my README..
